#ifndef __KCPTubeGeneratorStepByStep__
#define __KCPTubeGeneratorStepByStep__

/**
@file
Subclass of StepByStep, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/msgdlg.h>
#include <wx/intl.h>
#include "../others/configurations.hpp"
#include "../others/ui_languages.hpp"

/** Implementing StepByStep */
class KCPTubeGeneratorStepByStep : public StepByStep
{
	protected:
		// Handlers for StepByStep events.
		void Step2EncryptionOnChoice( wxCommandEvent& event );
		void Step3MTUOnCheckBox( wxCommandEvent& event );
		void Step3DPortRefreshOnCheckBox( wxCommandEvent& event );
		void Step3UDPTimeoutOnCheckBox( wxCommandEvent& event );
		void Step3KeepAliveOnCheckBox( wxCommandEvent& event );
		void Step3MuxTunnelsOnCheckBox( wxCommandEvent& event );
		void Step4SaveFileOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		KCPTubeGeneratorStepByStep( wxWindow* parent );
	//// end generated class members










private:
	void PutTextOnScreen();
	void AdjustUI();
	bool VerifyUserSelections();
	void CreateUserSettingFile();

	std::map<languages::steps_text_id, wxString> steps_text_id_to_text;
	std::map<languages::setting_options_id, wxString> setting_options_id_to_text;
	std::map<kcp_mode, wxString> kcp_mode_to_text;
	std::map<encryption_mode, wxString> encryption_mode_to_text;
};

#endif // __KCPTubeGeneratorStepByStep__
