#ifndef __KCPTubeGeneratorUserInput__
#define __KCPTubeGeneratorUserInput__

/**
@file
Subclass of UserInput, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/intl.h>
#include <wx/msgdlg.h>
#include "../others/ui_languages.hpp"

/** Implementing UserInput */
class KCPTubeGeneratorUserInput : public UserInput
{
	protected:
		// Handlers for UserInput events.
		void ClientKCPProfileOnChoice( wxCommandEvent& event );
		void ClientListenAddressOnCheckBox( wxCommandEvent& event );
		void ClientDestinationPortOnChoice( wxCommandEvent& event );
		void ClientDPortRefreshOnCheckBox( wxCommandEvent& event );
		void ClientUDPTimeoutOnCheckBox( wxCommandEvent& event );
		void ClientKeepAliveOnCheckBox( wxCommandEvent& event );
		void ClientMuxTunnelsOnCheckBox( wxCommandEvent& event );
		void ClientMTUOnCheckBox( wxCommandEvent& event );
		void ClientIPv4OnlyOnCheckBox( wxCommandEvent& event );
		void ClientEncrypitonOnChoice( wxCommandEvent& event );
		void ClientLogPathOnCheckBox( wxCommandEvent& event );
		void ClientVerifyAndSaveOnButtonClick( wxCommandEvent& event );
		void RelayFromClientKCPProfileOnChoice( wxCommandEvent& event );
		void RelayToServerKCPProfileOnChoice( wxCommandEvent& event );
		void RelayListenAddressOnCheckBox( wxCommandEvent& event );
		void RelayListenPortOnChoice( wxCommandEvent& event );
		void RelayFromClientUDPTimeoutOnCheckBox( wxCommandEvent& event );
		void RelayFromClientKeepAliveOnCheckBox( wxCommandEvent& event );
		void RelayFromClientMTUOnCheckBox( wxCommandEvent& event );
		void RelayFromClientIPv4OnlyOnCheckBox( wxCommandEvent& event );
		void RelayDestinationPortOnChoice( wxCommandEvent& event );
		void RelayDPortRefreshOnCheckBox( wxCommandEvent& event );
		void RelayToServerUDPTimeoutOnCheckBox( wxCommandEvent& event );
		void RelayToServerKeepAliveOnCheckBox( wxCommandEvent& event );
		void RelayToServerMTUOnCheckBox( wxCommandEvent& event );
		void RelayToServerIPv4OnlyOnCheckBox( wxCommandEvent& event );
		void RelayFromClientEncrypitonOnChoice( wxCommandEvent& event );
		void RelayToServerEncrypitonOnChoice( wxCommandEvent& event );
		void RelayVerifyAndSaveOnButtonClick( wxCommandEvent& event );
		void RelayKCPProfileOnChoice( wxCommandEvent& event );
		void ServerListenAddressOnCheckBox( wxCommandEvent& event );
		void ServerUDPTimeoutOnCheckBox( wxCommandEvent& event );
		void ServerKeepAliveOnCheckBox( wxCommandEvent& event );
		void ServerMTUOnCheckBox( wxCommandEvent& event );
		void ServerIPv4OnlyOnCheckBox( wxCommandEvent& event );
		void ServerStunServerOnCheckBox( wxCommandEvent& event );
		void ServerLogPathOnCheckBox( wxCommandEvent& event );
		void ServerEncrypitonOnChoice( wxCommandEvent& event );
		void ServerVerifyAndSaveOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		KCPTubeGeneratorUserInput( wxWindow* parent );
	//// end generated class members















private:
	void PutTextOnScreen();
	void AdjustUI();
	void ResetClientValues();
	void ResetRelayFcValues();
	void ResetRelayTsValues();
	void ResetServerValues();
	bool VerifyClientSelections();
	bool VerifyRelaySelections();
	bool VerifyServerSelections();
	void CreateClientSettingFile();
	void CreateRelaySettingFile();
	void CreateServerSettingFile();

	std::map<languages::userinput_text_id, wxString> userinput_text_id_to_text;
	std::map<languages::setting_options_id, wxString> setting_options_id_to_text;
	std::map<kcp_mode, wxString> kcp_mode_to_text;
	std::map<encryption_mode, wxString> encryption_mode_to_text;
};

#endif // __KCPTubeGeneratorUserInput__
