#ifndef __KCPTubeGeneratorEntrance__
#define __KCPTubeGeneratorEntrance__

/**
@file
Subclass of Entrance, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <memory>
#include <wx/intl.h>
#include <fstream>
#include "KCPTubeGeneratorStepByStep.h"
#include "KCPTubeGeneratorUserInput.h"
#include "../others/ui_languages.hpp"

/** Implementing Entrance */
class KCPTubeGeneratorEntrance : public Entrance
{
	protected:
		// Handlers for Entrance events.
		void EntranceStepbyStepOnButtonClick( wxCommandEvent& event );
		void EntranceUserInputOnButtonClick( wxCommandEvent& event );
		void EntranceVerifyFileOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		KCPTubeGeneratorEntrance( wxWindow* parent );
	//// end generated class members






private:
		void PutTextOnScreen();
		void AdjustUI();

		std::map<languages::entrance_text_id, wxString> entrance_text_id_to_text;
};

#endif // __KCPTubeGeneratorEntrance__
